Repository TGLuis/compteurDeLaRoulotte, pull requests merged in 2020-09, with the labels that each got.

#1 Tools menu
  lecompteurdelaroulotte/app/src/main/java/fragments/ConverterFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ToolsFragment.kt
  lecompteurdelaroulotte/app/src/main/java/tgl/lecompteurdelaroulotte/MainActivity.kt
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_about.xml
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_converter.xml
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_tools.xml
  lecompteurdelaroulotte/app/src/main/res/values-fr/strings.xml
  lecompteurdelaroulotte/app/src/main/res/values-nl/strings.xml
  lecompteurdelaroulotte/app/src/main/res/values/dimens.xml
  lecompteurdelaroulotte/app/src/main/res/values/strings.xml
Labels: enhancement

#4 Refactoring
  lecompteurdelaroulotte/app/build.gradle
  lecompteurdelaroulotte/app/src/main/java/fragments/AboutFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ArchiveFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/CommentFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ConverterFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/HelpFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/HomeFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/MyFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/NotesFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ParametersFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/RuleFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/SeeFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ToolsFragment.kt
  lecompteurdelaroulotte/app/src/main/java/library/Helper.kt
  lecompteurdelaroulotte/app/src/main/java/library/MyDatabase.kt
  lecompteurdelaroulotte/app/src/main/java/tgl/lecompteurdelaroulotte/MainActivity.kt
  lecompteurdelaroulotte/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_add_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_archive_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_arrow_drop_up_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_delete_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_delete_outline_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_info_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_link_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_picture_as_pdf_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_save_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_unarchive_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_visibility_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_baseline_visibility_off_24.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/ic_launcher_background.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/pressed_round_outlined_grey_filled.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/round_outlined.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/round_outlined_grey_filled.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/selector_round_outlined_grey_filled.xml
  lecompteurdelaroulotte/app/src/main/res/drawable/shadow_button_layer_list.xml
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_converter.xml
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_rule.xml
  lecompteurdelaroulotte/app/src/main/res/layout/fragment_tools.xml
  lecompteurdelaroulotte/app/src/main/res/layout/list_step_item.xml
  lecompteurdelaroulotte/app/src/main/res/values-nl/dimens.xml
  lecompteurdelaroulotte/app/src/main/res/values/dimens.xml
  lecompteurdelaroulotte/build.gradle
Labels: bug, enhancement

#7 new big refactoring: extract function + extract Dialog class
  lecompteurdelaroulotte/app/src/main/java/fragments/ArchiveFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/CommentFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ConverterFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/CounterFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/HelpFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/HomeFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ParametersFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/ProjectFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/RuleFragment.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/SeeComments.kt
  lecompteurdelaroulotte/app/src/main/java/fragments/SeeRules.kt
  lecompteurdelaroulotte/app/src/main/java/library/Dialogs.kt
  lecompteurdelaroulotte/app/src/main/java/library/Helper.kt
  lecompteurdelaroulotte/app/src/main/java/library/Listeners.kt
Labels: refactoring
